alias: test_actions_stream
id: iurjtknvisfnwrlkuvsklfmwcjdjfmsdfmgv
trigger: 
  platform: event
  event_type: mobile_app_notification_action
  event_data:
    action: turn on office_lamp
action:
  - service: light.turn_on
    data:
      entity_id: light.677883783c71bf30d1f5