##############################################################################
# The devices created below are essential to the page control automations
# and you'll probably want to carry them over to your own configuration
homeassistant:
  customize:
    input_number.hasp_mrszzs_alarmcode1:
      hidden: true
    input_number.hasp_mrszzs_alarmcode2:
      hidden: true
    input_number.hasp_mrszzs_alarmcode3:
      hidden: true
    input_number.hasp_mrszzs_alarmcode4:
      hidden: true

# Enable this iframe to integrate the HASP web admin panel in Hass.
# This will not work if you have SSL enabled, see details here:
# https://www.home-assistant.io/components/panel_iframe/
#
# panel_iframe:
#   mrszzs:
#     title: "mrszzs"
#     url: "http://mrszzs"
#     icon: "mdi:cellphone-text"

light:
  - platform: mqtt
    name: mrszzs Backlight
    command_topic: "hasp/mrszzs/light/switch"
    state_topic: "hasp/mrszzs/light/state"
    brightness_state_topic: "hasp/mrszzs/brightness/state"
    brightness_command_topic: "hasp/mrszzs/brightness/set"
    availability_topic: "hasp/mrszzs/status"
    payload_available: "ON"
    payload_not_available: "OFF"

binary_sensor:
  - platform: mqtt
    name: mrszzs Connected
    device_class: connectivity
    state_topic: "hasp/mrszzs/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/mrszzs/status"
    payload_available: "ON"
    payload_not_available: "OFF"

sensor:
  - platform: mqtt
    name: mrszzs Sensor
    state_topic: "hasp/mrszzs/sensor"
    json_attributes_template: '{{ value_json.status }}'
    # json_attributes:
    #   - espVersion
    #   - updateESPAvailable
    #   - lcdVersion
    #   - updateLcdAvailable
    #   - espUptime
    #   - signalStrength
    #   - haspIP

input_text:
  hasp_mrszzs_pagebutton1label:
    name: mrszzs Page 1 Label
    icon: mdi:book-open-page-variant
  hasp_mrszzs_pagebutton2label:
    name: mrszzs Page 2 Label
    icon: mdi:book-open-page-variant
  hasp_mrszzs_pagebutton3label:
    name: mrszzs Page 3 Label
    icon: mdi:book-open-page-variant

input_number:
  hasp_mrszzs_pagebutton1page:
    name: mrszzs Page 1 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_mrszzs_pagebutton2page:
    name: mrszzs Page 2 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_mrszzs_pagebutton3page:
    name: mrszzs Page 3 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_mrszzs_activepage:
    name: mrszzs Active Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_mrszzs_alarmcode1:
    name: mrszzs AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_mrszzs_alarmcode2:
    name: mrszzs AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_mrszzs_alarmcode3:
    name: mrszzs AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_mrszzs_alarmcode4:
    name: mrszzs AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

group:
  mrszzs:
    name: mrszzs
    entities:
      - binary_sensor.mrszzs_connected
      - sensor.mrszzs_sensor
      - light.mrszzs_backlight
      - group.mrszzs_pageselect
      - group.mrszzs_colors
      - group.mrszzs_automations
  mrszzs_pageselect:
    name: mrszzs Page Selection
    entities:
      - input_number.hasp_mrszzs_activepage
      - input_number.hasp_mrszzs_pagebutton1page
      - input_text.hasp_mrszzs_pagebutton1label
      - input_number.hasp_mrszzs_pagebutton2page
      - input_text.hasp_mrszzs_pagebutton2label
      - input_number.hasp_mrszzs_pagebutton3page
      - input_text.hasp_mrszzs_pagebutton3label
  mrszzs_automations:
    name: mrszzs automations
    entities:
      - automation.hasp_mrszzs_00_firsttimesetup

automation:
##############################################################################
# Run first time setup commands
  - alias: hasp_mrszzs_00_FirstTimeSetup
    trigger: []
    action:
      - service: automation.trigger
        data:
          entity_id: 'automation.hasp_mrszzs_00_automationgroupupdate'
      - service: homeassistant.turn_on
        data:
          entity_id: 'group.mrszzs_automations'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_mrszzs_pagebutton1label'
          value: 'scenes'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_mrszzs_pagebutton2label'
          value: 'status'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_mrszzs_pagebutton3label'
          value: 'lights'
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_pagebutton1page'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_pagebutton2page'
          value: 2
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_pagebutton3page'
          value: 3
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_activepage'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_selectedforegroundcolor'
          value: 0
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_selectedbackgroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_unselectedforegroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_mrszzs_unselectedbackgroundcolor'
          value: 25388

##############################################################################
# Set automation group members on start - Thanks @Nightcat!
  - alias: hasp_mrszzs_00_AutomationGroupUpdate
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: group.set
      data_template:
        object_id: "mrszzs_automations"
        entities: >-
          {%- for item in states.automation if ((item.entity_id | lower).startswith('automation.hasp_mrszzs_')) -%}
          {{ item.entity_id }}
          {% if not loop.last %}, {% endif %}
          {%- endfor -%}