##############################################################################
# Automations and required components to display information messages on HASP

input_text:
  hasp_desk_messagetext:
    name: desk Message Text
    icon: mdi:playlist-edit
    max: 126
  hasp_desk_messageqr:
    name: desk Message QR
    icon: mdi:qrcode-edit
    max: 47

input_number:
  hasp_desk_messagetime:
    name: desk Message Time
    icon: mdi:clock-end
    mode: box
    min: 1
    max: 600
    step: 1

group:
  desk_messagedisplay:
    name: desk Message Display
    entities:
      - input_text.hasp_desk_messagetext
      - input_text.hasp_desk_messageqr
      - input_number.hasp_desk_messagetime
      - automation.hasp_desk_00_messagedisplaytext
      - automation.hasp_desk_00_messagedisplayqr
      - automation.hasp_desk_00_messagedisplaytextqr

automation:
##############################################################################
# Display text message only
  - alias: hasp_desk_00_messagedisplaytext
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/desk/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_desk_messagetext.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 1,1'
    - delay: '00:00:{{ states.input_number.hasp_desk_messagetime.state | int }}'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/desk/command/page'
        payload: '{{ states.input_number.hasp_desk_activepage.state | int }}'

##############################################################################
# Display qr message only
  - alias: hasp_desk_00_messagedisplayqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/desk/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_desk_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 1,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_desk_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/desk/command/page'
        payload: '{{ states.input_number.hasp_desk_activepage.state | int }}'

##############################################################################
# Display text and qr message
  - alias: hasp_desk_00_messagedisplaytextqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/desk/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_desk_messagetext.state }}"'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/desk/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_desk_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_desk_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/desk/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/desk/command/page'
        payload: '{{ states.input_number.hasp_desk_activepage.state | int }}'