sensor:
- platform: template
  sensors:
    # 3D Printer sensors
    # hotend:
    #   friendly_name: 'Hotend'
    #   value_template: '{{ ((states.sensor.octoprint_actual_tool0_temp.state | float-32) | float*(5/9)) | round(1) }}'
    #   # NOT WORKING - unit_of_measurement: "°C"
    # bed:
    #   friendly_name: "Bed"
    #   value_template: '{{ ((states.sensor.octoprint_actual_bed_temp.state | float-32) | float*(5/9)) | round(1) }}'
    #   # NOT WORKING - unit_of_measurement: "°C"
    printing_status:
      friendly_name: 'Printing Status'
      value_template: '{{states.binary_sensor.octoprint_printing.state}}'
      icon_template: '{% if is_state("binary_sensor.octoprint_printing", "off") %}mdi:sleep{% else %}mdi:printer-3d{% endif %}'
    # printing_error_status:
    #   friendly_name: 'Printing Error Status'
    #   value_template: '{{states.binary_sensor.octoprint_printing_error.state}}'
    #   icon_template: '{% if is_state("binary_sensor.octoprint_printing_error", "off") %}mdi:thumb-up-outline{% else %}mdi:thumb-down{% endif %}'

#OctoPrint
- platform: octoprint
  name: OctoPrint
  monitored_conditions:
    - Current State
#        - Temperatures
    - Job Percentage
    
binary_sensor:
- platform: octoprint
  monitored_conditions:
  - Printing
  - Printing Error