automation:
##############################################################################
# Auto update firmware at 3:00am every day if a new version is available
  - alias: hasp_bench_00_AutoFirmwareUpdate
    trigger:
      - platform: time
        at: '3:00:00'
    condition:
    - condition: template
      value_template: '{{ states.sensor.bench_status.attributes.updateESPAvailable == true }}'
    - condition: state
      entity_id: 'binary_sensor.bench_connected'
      state: 'on'
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/espupdate'
        payload: ''