##############################################################################
# Automations and required components to display information messages on HASP

input_text:
  hasp_bench_messagetext:
    name: bench Message Text
    icon: mdi:playlist-edit
    max: 126
  hasp_bench_messageqr:
    name: bench Message QR
    icon: mdi:qrcode-edit
    max: 47

input_number:
  hasp_bench_messagetime:
    name: bench Message Time
    icon: mdi:clock-end
    mode: box
    min: 1
    max: 600
    step: 1

group:
  bench_messagedisplay:
    name: bench Message Display
    entities:
      - input_text.hasp_bench_messagetext
      - input_text.hasp_bench_messageqr
      - input_number.hasp_bench_messagetime
      - automation.hasp_bench_00_messagedisplaytext
      - automation.hasp_bench_00_messagedisplayqr
      - automation.hasp_bench_00_messagedisplaytextqr

automation:
##############################################################################
# Display text message only
  - alias: hasp_bench_00_messagedisplaytext
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_bench_messagetext.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 1,1'
    - delay: '00:00:{{ states.input_number.hasp_bench_messagetime.state | int }}'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/page'
        payload: '{{ states.input_number.hasp_bench_activepage.state | int }}'

##############################################################################
# Display qr message only
  - alias: hasp_bench_00_messagedisplayqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_bench_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 1,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_bench_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/page'
        payload: '{{ states.input_number.hasp_bench_activepage.state | int }}'

##############################################################################
# Display text and qr message
  - alias: hasp_bench_00_messagedisplaytextqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_bench_messagetext.state }}"'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_bench_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_bench_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/page'
        payload: '{{ states.input_number.hasp_bench_activepage.state | int }}'