##############################################################################
# Automations and required components to display information messages on HASP

input_text:
  hasp_mrszzs_messagetext:
    name: mrszzs Message Text
    icon: mdi:playlist-edit
    max: 126
  hasp_mrszzs_messageqr:
    name: mrszzs Message QR
    icon: mdi:qrcode-edit
    max: 47

input_number:
  hasp_mrszzs_messagetime:
    name: mrszzs Message Time
    icon: mdi:clock-end
    mode: box
    min: 1
    max: 600
    step: 1

group:
  mrszzs_messagedisplay:
    name: mrszzs Message Display
    entities:
      - input_text.hasp_mrszzs_messagetext
      - input_text.hasp_mrszzs_messageqr
      - input_number.hasp_mrszzs_messagetime
      - automation.hasp_mrszzs_00_messagedisplaytext
      - automation.hasp_mrszzs_00_messagedisplayqr
      - automation.hasp_mrszzs_00_messagedisplaytextqr

automation:
##############################################################################
# Display text message only
  - alias: hasp_mrszzs_00_messagedisplaytext
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/mrszzs/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_mrszzs_messagetext.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 1,1'
    - delay: '00:00:{{ states.input_number.hasp_mrszzs_messagetime.state | int }}'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/mrszzs/command/page'
        payload: '{{ states.input_number.hasp_mrszzs_activepage.state | int }}'

##############################################################################
# Display qr message only
  - alias: hasp_mrszzs_00_messagedisplayqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/mrszzs/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_mrszzs_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 1,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_mrszzs_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/mrszzs/command/page'
        payload: '{{ states.input_number.hasp_mrszzs_activepage.state | int }}'

##############################################################################
# Display text and qr message
  - alias: hasp_mrszzs_00_messagedisplaytextqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/mrszzs/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_mrszzs_messagetext.state }}"'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/mrszzs/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_mrszzs_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_mrszzs_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/mrszzs/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/mrszzs/command/page'
        payload: '{{ states.input_number.hasp_mrszzs_activepage.state | int }}'