##############################################################################
# Automations and required components to display information messages on HASP

input_text:
  hasp_tower_messagetext:
    name: tower Message Text
    icon: mdi:playlist-edit
    max: 126
  hasp_tower_messageqr:
    name: tower Message QR
    icon: mdi:qrcode-edit
    max: 47

input_number:
  hasp_tower_messagetime:
    name: tower Message Time
    icon: mdi:clock-end
    mode: box
    min: 1
    max: 600
    step: 1

group:
  tower_messagedisplay:
    name: tower Message Display
    entities:
      - input_text.hasp_tower_messagetext
      - input_text.hasp_tower_messageqr
      - input_number.hasp_tower_messagetime
      - automation.hasp_tower_00_messagedisplaytext
      - automation.hasp_tower_00_messagedisplayqr
      - automation.hasp_tower_00_messagedisplaytextqr

automation:
##############################################################################
# Display text message only
  - alias: hasp_tower_00_messagedisplaytext
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/tower/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_tower_messagetext.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 1,1'
    - delay: '00:00:{{ states.input_number.hasp_tower_messagetime.state | int }}'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/tower/command/page'
        payload: '{{ states.input_number.hasp_tower_activepage.state | int }}'

##############################################################################
# Display qr message only
  - alias: hasp_tower_00_messagedisplayqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/tower/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_tower_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 1,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_tower_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/tower/command/page'
        payload: '{{ states.input_number.hasp_tower_activepage.state | int }}'

##############################################################################
# Display text and qr message
  - alias: hasp_tower_00_messagedisplaytextqr
    trigger: []
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/tower/command/p[0].b[1].txt'
        payload: '"{{ states.input_text.hasp_tower_messagetext.state }}"'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/tower/command/p[0].b[3].txt'
        payload: '"{{ states.input_text.hasp_tower_messageqr.state }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command/page'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 1,1'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 3,1'
    - delay: '00:00:{{ states.input_number.hasp_tower_messagetime.state | int }}'
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command'
        payload: 'vis 3,0'
    - service: mqtt.publish
      data_template:
        topic: 'hasp/tower/command/page'
        payload: '{{ states.input_number.hasp_tower_activepage.state | int }}'