##############################################################################
# Automations for handling toggle state buttons on page 3
automation:
  # Set font and text for toggle buttons on device connection
  - alias: hasp_bench_p3_ToggleInit
    trigger:
    - platform: state
      entity_id: 'binary_sensor.bench_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[4].font'
        payload: '3'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[4].txt'
        payload: '"Light"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[5].font'
        payload: '3'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[5].txt'
        payload: '"Fan"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[6].font'
        payload: '3'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[6].txt'
        payload: '"Crown"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[7].font'
        payload: '2'

  # Toggle light1 when p[3].b[4] pressed
  - alias: hasp_bench_p3_ToggleLight1
    trigger:
    - platform: mqtt
      topic: 'hasp/bench/state/p[3].b[4]'
      payload: 'ON'
    action:
    - service: switch.toggle
      entity_id: switch.office_light
      
  # Toggle light2 when p[3].b[5] pressed
  - alias: hasp_bench_p3_ToggleLight2
    trigger:
    - platform: mqtt
      topic: 'hasp/bench/state/p[3].b[5]'
      payload: 'ON'
    action:
    - service: switch.toggle
      entity_id: switch.office_fan  

  # Toggle light3 when p[3].b[6] pressed
  - alias: hasp_bench_p3_ToggleLight3
    trigger:
    - platform: mqtt
      topic: 'hasp/bench/state/p[3].b[6]'
      payload: 'ON'
    action:
    - service: switch.toggle
      entity_id: switch.office_crown

  # Toggle all light_toggle_group_office when p[3].b[7] pressed
  - alias: hasp_bench_p3_ToggleAll
    trigger:
    - platform: mqtt
      topic: 'hasp/bench/state/p[3].b[7]'
      payload: 'ON'
    action:
    - service_template: >
          {% if states.group.light_toggle_group_office.state == "on" -%}
            homeassistant.turn_off
          {%- else -%}
            homeassistant.turn_on
          {%- endif %}
      entity_id: group.light_toggle_group_office
      
  # Toggle colors on p[3].b[4] when light1 changes
  - alias: hasp_bench_p3_ToggleColor1
    trigger:
    - platform: state
      entity_id: switch.office_light
    - platform: state
      entity_id: 'binary_sensor.bench_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_bench_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[4].bco'
        payload_template: >-
          {% if states.switch.office_light.state == "on" -%}
            {{ states.input_number.hasp_bench_selectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_unselectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[3].b[4].pco'
        payload_template: >-
          {% if states.switch.office_light.state == "on" -%}
            {{ states.input_number.hasp_bench_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_unselectedforegroundcolor.state | int }}
          {%- endif %}

  # Toggle colors on p[3].b[5] when light1 changes
  - alias: hasp_bench_p3_ToggleColor2
    trigger:
    - platform: state
      entity_id: switch.office_fan
    - platform: state
      entity_id: 'binary_sensor.bench_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_bench_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[5].bco'
        payload_template: >-
          {% if states.switch.office_fan.state == "on" -%}
            {{ states.input_number.hasp_bench_selectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_unselectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[3].b[5].pco'
        payload_template: >-
          {% if states.switch.office_fan.state == "on" -%}
            {{ states.input_number.hasp_bench_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_unselectedforegroundcolor.state | int }}
          {%- endif %}

  # Toggle colors on p[3].b[6] when light1 changes
  - alias: hasp_bench_p3_ToggleColor3
    trigger:
    - platform: state
      entity_id: switch.office_crown
    - platform: state
      entity_id: 'binary_sensor.bench_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_bench_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[6].bco'
        payload_template: >-
          {% if states.switch.office_crown.state == "on" -%}
            {{ states.input_number.hasp_bench_selectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_unselectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[3].b[6].pco'
        payload_template: >-
          {% if states.switch.office_crown.state == "on" -%}
            {{ states.input_number.hasp_bench_selectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_unselectedforegroundcolor.state | int }}
          {%- endif %}

  # Set button 4 to "All Off" if any lights are on, otherwise set to "All On"
  - alias: hasp_bench_p3_ToggleColorAll
    trigger:
    - platform: state
      entity_id: group.light_toggle_group_office
    - platform: state
      entity_id: 'binary_sensor.bench_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_bench_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_bench_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bench/command/p[3].b[7].bco'
        payload_template: >-
          {% if states.group.light_toggle_group_office.state == "on" -%}
            {{ states.input_number.hasp_bench_unselectedbackgroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_selectedbackgroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[3].b[7].pco'
        payload_template: >-
          {% if states.group.light_toggle_group_office.state == "on" -%}
            {{ states.input_number.hasp_bench_unselectedforegroundcolor.state | int }}
          {%- else -%}
            {{ states.input_number.hasp_bench_selectedforegroundcolor.state | int }}
          {%- endif %}
    - service: mqtt.publish
      data_template:
        topic: 'hasp/bench/command/p[3].b[7].txt'
        payload_template: >-
          {% if states.group.light_toggle_group_office.state == "on" -%}
           "Office Off"
          {%- else -%}
           "Office On"
          {%- endif %}