binary_sensor:
- platform: mqtt
  name: "Basment Water"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "84B90E"
  device_class: moisture
  qos: 1
