binary_sensor:
- platform: mqtt
  state_topic: "tele/RF_Bridge/RESULT"
  name: 'Boys Bathroom Motion'
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: 'E1278E'
  payload_off: 'E1278Eoff'
  device_class: motion
  off_delay: 5
  qos: 1