binary_sensor:
- platform: mqtt
  name: "Office Window"
  state_topic: "tele/RF_Bridge/RESULT"
  value_template: '{{value_json.RfReceived.Data}}'
  payload_on: "9E7A0A"
  payload_off: "9E7A0E"
  device_class: window
  qos: 1