id: alexabedtimeaction
alias: alexa_bedtime_action
trigger:
    platform: event
    event_type: alexa_actionable_notificaiton
    event_data:
      event_id: actionable_notification_bedtime
      event_response: ResponseYes
    
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.bedtime