##############################################################################
# Automations and required components to configure colors on the HASP panel
#
# Check out this site for easy color code selection and conversion:
# https://nodtem66.github.io/nextion-hmi-color-convert/index.html

input_number:
  hasp_entryway_selectedforegroundcolor:
    name: entryway Selected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_entryway_selectedbackgroundcolor:
    name: entryway Selected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_entryway_unselectedforegroundcolor:
    name: entryway Unselected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_entryway_unselectedbackgroundcolor:
    name: entryway Unselected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
group:
  entryway_colors:
    name: entryway Colors
    entities:
      - input_number.hasp_entryway_selectedforegroundcolor
      - input_number.hasp_entryway_selectedbackgroundcolor
      - input_number.hasp_entryway_unselectedforegroundcolor
      - input_number.hasp_entryway_unselectedbackgroundcolor
